services:
  db:
    image: postgres:15
    container_name: gestante-db-dev
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gestanteapp
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  backend:
    image: mcr.microsoft.com/dotnet/sdk:10.0
    container_name: gestante-backend-dev
    volumes:
      - ./backend:/src
      - /src/bin
      - /src/obj
    working_dir: /src
    command: dotnet watch run --urls=http://0.0.0.0:8080
    ports:
      - "5167:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_HOST=db
      - DB_NAME=gestanteapp
      - DB_USER=user
      - DB_PASSWORD=password
    depends_on:
      - db

  frontend:
    image: node:20-alpine
    container_name: gestante-frontend-dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm config set fetch-retry-maxtimeout 120000 && npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://127.0.0.1:5167/api
    depends_on:
      - backend

volumes:
  postgres_data:
